# Site settings
title: Site Title
email: your-email@domain.com
description: Site Description
# Build settings
markdown: kramdown
exclude:
  - node_modules
  - README.md
sass:
  sass_dir: assets/css
  style: :nested
